import React from "react";

const Prescriptions = () => {
  // Dummy data representing prescriptions generated by the Doctor Module
  const myPrescriptions = [
    { id: 101, doctor: "Dr. Ahmed", date: "2025-12-20", diagnosis: "Hypertension", medication: "Amlodipine 5mg" },
    { id: 102, doctor: "Dr. Sarah", date: "2025-11-15", diagnosis: "Skin Allergy", medication: "Cetirizine" },
  ];

  const handleDownload = (id) => {
    alert(`Downloading Digital Prescription PDF for record #${id}`);
  };

  return (
    <div className="p-6 border rounded-lg shadow-md bg-white">
      <h2 className="text-2xl font-bold mb-4 text-blue-600">My Prescriptions</h2>
      <div className="overflow-x-auto">
        <table className="w-full text-left border-collapse">
          <thead>
            <tr className="border-b bg-gray-50">
              <th className="p-3 font-semibold text-gray-700">Date</th>
              <th className="p-3 font-semibold text-gray-700">Doctor</th>
              <th className="p-3 font-semibold text-gray-700">Diagnosis</th>
              <th className="p-3 font-semibold text-gray-700">Action</th>
            </tr>
          </thead>
          <tbody>
            {myPrescriptions.map((px) => (
              <tr key={px.id} className="border-b hover:bg-gray-50 transition">
                <td className="p-3">{px.date}</td>
                <td className="p-3">{px.doctor}</td>
                <td className="p-3">{px.diagnosis}</td>
                <td className="p-3">
                  <button 
                    onClick={() => handleDownload(px.id)}
                    className="text-blue-500 hover:underline font-medium"
                  >
                    Download PDF
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default Prescriptions;